# Define the required macros
CFLAGS = -Wall -Werror -Wextra -Wstrict-prototypes -Wformat=2 -pedantic -fno-common -ftrapv -O3 -g -std=gnu11
CC = gcc52
LDLIBS = -lm
OBJ = mypopen.o
HEADER = mypopen.h
TEST = popentest

all: mypopen.c
    $(CC) $(CFLAGS) -c $(HEADER) $(TEST).c

# link against the testfolder on annuminas
test: $(OBJ)
    $(CC) -o$(TEST) $(OBJ) -lpopentest -ldl

# link against the dynamic test suite test-pipe
test-pipe: $(OBJ)
    $(CC) -o test-pipe $(OBJ) -ltest-pipe

.phony : clean

clean:
	rm -f *.o mypopen


# todo: insert doxy generator rule